### ISSUE TITLE
Refactor code related to adopter foster profile in seed files using lambda

### ISSUE THREAD

**Issue by atbalaji** [rubyforgood/homeward-tails#721]
- To avoid code redundancy for adopter_foster_profile params rewrite them using lambda
- Refer the recently added implementation using lambda for any doubts

**Comment by felicia22** [comment]
Hi, I would like to work on this issue. Do you have any specific details on which files/where specifically on the code redundancy? (sorry, I'm trying to contribute to an open source project for a class and might need a little bit of help getting started)

**Comment by coalest** [comment]
Hey @felicia22! I think this task is outdated and could probably be closed. Looking at [this seed file](https://github.com/rubyforgood/pet-rescue/commit/07a641bba789559f03eeeb50bced07b6efee874f#diff-02d8f4d1d92e7df82f4c8891106567ac252dbe93758acba470918355efaa5c82) from a PR submitted right before this issue was opened, we can get an idea of what this issue was probably asking for.

But considering the model `AdopterFosterProfile` has been renamed/dropped and the `db/seeds/*` file structure no longer looks similar, I'm not sure if this is necessary any longer.
